# PostgreSQL へ接続する
$ psql -h ホスト名 -p ポート番号 -U ロール名 -d データベース名

$ psql -U kkmatsuo -d tbiapp2

で、tbiapp=> が表示されて、db操作できる。(ローカル環境に限る)

再開時のエラーには、
$ sudo service postgresql start

************** 導入 ********************
まずPostgreSQLとそれに必要なツール群のインストールです。
sudo apt update
sudo apt install -y python3-pip 済　python3-dev済 libpq-dev未 postgresql postgresql-contrib

$ psql --version
psql (PostgreSQL) 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1)

$ sudo -u postgres psql

==================================================================
psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

のerror出現。
　→sudo /etc/init.d/postgresql start
と打てばOK
"""
sudo service postgresql start
sudo service postgresql stop
も同じ使い方とのこと
"""

tbiappを新しく作った後も同じエラーが出て、同じ方法で解決した。
=================================================================

# 1.2. Ubuntu の場合
# 起動
sudo service postgresql start
# 停止
sudo service postgresql stop
# 再起動
# なし pg_ctl で再起動する。

postgres=# CREATE DATABASE myapp;
CREATE DATABASE

postgres=# CREATE USER kkmatsuo WITH PASSWORD 'Pbasuke2688';
CREATE ROLE

postgres=# ALTER ROLE kkmatsuo SET client_encoding TO 'utf8';
ALTER ROLE

postgres=# ALTER ROLE kkmatsuo SET default_transaction_isolation TO 'read committed';
ALTER ROLE

postgres=# ALTER ROLE kkmatsuo SET timezone TO 'Asia/Tokyo';
ALTER ROLE     
           ^
postgres=# GRANT ALL PRIVILEGES ON DATABASE myapp TO kkmatsuo;
GRANT

以上を行った。2021/6/2
****************************************************

$ psql -U kkmatsuo -d tbiapp2
で、tbiapp=> が表示されてOK.

===============================
データやりくりでmigrateできなくなっちゃったので、上記の方法で
tbiappを新たに作って、djangoに使うdbをmyappからtbiappに変更。
2021/6/18
===============================

===============================
データやりくりでmigrateできなくなっちゃったので、上記の方法で
tbiappを新たに作って、djangoに使うdbをmyappからtbiappに変更。
2021/6/21

migtrations fileの処理は、以下参考
https://sinyblog.com/django/drop_table_001/
===============================


テーブルの一覧は\dで表示できます。
以上を終えたら\qでログアウトして終了.

拡張表示をONにする
blogapp=> \x

データの確認
myapp=> select * from [Table名];

Table ENDから抜ける時は、q

postgresqlの終わり方がちゃんとしていないことで？
再接続時に以下のエラーが出た。

psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

The above exception was the direct cause of the following exception:

django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

以下のコマンドで解決した。
sudo service postgresql start
=============================================

psycopg2.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "users_user"
The above exception was the direct cause of the following exception:
解決法...
